### ISSUE TITLE
betweenness centrality not correct

### ISSUE THREAD

**Issue by schochastics** [SebastianSosa/ANTs#3]
The function `met.betweenness()` seems to give the wrong betweenness value.
```r
library(igraph)
library(ANTs)

A <- structure(c(0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 
            1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 
            0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 
            1, 1, 1, 1, 0), .Dim = c(8L, 8L))

ga <- graph_from_adjacency_matrix(A,"undirected")
betweenness(ga)
#> [1]  0.000000  0.000000  0.333333  0.000000  1.833333  0.000000  0.000000 12.833333
met.betweenness(A)
#> [1]  0  0  0  0  0  0  0 15
```

I tested it with several random binary, symmetric networks and it always gives very different results compared to igraph. The reprex above is an extreme case (i.e. the error does not stem from different normalizations).

**Comment by ivanpugagonzalez** [comment]
Pfff who is that dude...?
I am pretty sure he is doing one of the errors I was previously doing.

Ivan

**Comment by schochastics** [comment]
@ivanpugagonzalez  No need to be condescending. I was just pointing out that I got a wrong result using `met.betweenness()`. If I am using the function wrong, please do let me know

**Comment by ivanpugagonzalez** [comment]
Dear David,

I appreciate you checking the function.
I was pointing out an error I was previously doing with this same function.
I did not mean to be condescending and if somehow I did so, I apologize.

I will check the function asap and come back to you.

Kind regards,
Ivan

**Comment by ivanpugagonzalez** [comment]
Dear David,

Thank you for your interest in ANTs and for highlighting an issue with the met.betweenness function. We had had previously a problem with floating points, and on fixing this problem we ended up introducing a bug. We have now fixed this problem and updated the code.

Please also note that the default arguments in the met.betwenness function get the reciprocal values of the matrix (i.e. 1/x) in order to compute the shortest path through links with higher strength. Igraph, by default, does the opposite, computes the shortest path through links with the lowest strength.

If you find any other problems with the code do not hesitate to contact us. We are happy to have feedback from users and to solve any issues they may find as fast as possible.

Kind regards,
Ivan
